name: 'Multi-Style Contribution Snake'
description: 'Generates 4 unique styles of contribution snakes (Blocks, Rounds, Triangles, Stars) with auto-username detection.'
author: 'Pro-Bandey'
branding:
  icon: 'play'
  color: 'green'

inputs:
  github_user_name:
    description: 'The GitHub username to generate the snake for'
    required: true
    default: ${{ github.repository_owner }}

runs:
  using: "composite"
  steps:
    - name: Create dist folder
      run: mkdir -p dist
      shell: bash

    # 1. Light Style - Blocks
    - name: Generate Light Snake
      uses: Platane/snk@v3
      with:
        github_user_name: ${{ inputs.github_user_name }}
        outputs: |
          dist/github-snake-light-blocks.svg?palette=github-light&color_snake=orange&custom_css=.month{fill:#333;font-weight:bold;}
          dist/github-snake-light-blocks.gif?palette=github-light&color_snake=orange&color_background=#ffffff

    # 2. Dark Style - Rounds
    - name: Generate Dark Snake
      uses: Platane/snk@v3
      with:
        github_user_name: ${{ inputs.github_user_name }}
        outputs: |
          dist/github-snake-dark-rounds.svg?palette=github-dark&color_snake=#fe2&shape=circle&custom_css=.month{fill:#fe2;}
          dist/github-snake-dark-rounds.gif?palette=github-dark&color_snake=#fe2&shape=circle&color_background=#0d1117

    # 3. Ocean Style - Triangles
    - name: Generate Ocean Snake
      uses: Platane/snk@v3
      with:
        github_user_name: ${{ inputs.github_user_name }}
        outputs: |
          dist/github-snake-ocean-triangles.svg?color_snake=#00fff2&color_dots=#05152c,#03415e,#025d84,#0176a7,#008fc9&custom_css=rect.ContributionCalendar-day{clip-path:polygon(50% 0%, 0% 100%, 100% 100%);}.month{fill:#00fff2;}
          dist/github-snake-ocean-triangles.gif?color_snake=#00fff2&color_dots=#05152c,#03415e,#025d84,#0176a7,#008fc9&color_background=#05152c

    # 4. Dracula Style - Stars
    - name: Generate Dracula Snake
      uses: Platane/snk@v3
      with:
        github_user_name: ${{ inputs.github_user_name }}
        outputs: |
          dist/github-snake-dracula-stars.svg?color_snake=#ff79c6&color_dots=#282a36,#44475a,#6272a4,#bd93f9,#ff79c6&custom_css=rect.ContributionCalendar-day{clip-path:polygon(50% 0%, 61% 35%, 98% 35%, 68% 57%, 79% 91%, 50% 70%, 21% 91%, 32% 57%, 2% 35%, 39% 35%);}.month{fill:#bd93f9;}
          dist/github-snake-dracula-stars.gif?color_snake=#ff79c6&color_dots=#282a36,#44475a,#6272a4,#bd93f9,#ff79c6&color_background=#282a36

    - name: Deploy to output branch
      uses: crazy-max/ghaction-github-pages@v4
      with:
        target_branch: output
        build_dir: dist
      env:
        GITHUB_TOKEN: ${{ github.token }}
